---
- name: installed apache
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present

  - name: running and enabled httpd
    service:
      name: httpd
      state: started
      enabled: yes
