# -*- mode: ruby -*-
# vi: set ft=ruby :

SOURCE = "../provision"
TARGET = "/vagrant"

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.synced_folder SOURCE, TARGET
  config.vm.box = "bento/centos-7.2"
  config.vm.network "private_network", ip: "192.168.33.22"
  config.vm.provision "ansible_local" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "#{TARGET}/main.yml"
    ansible.inventory_path = "#{TARGET}/hosts"
  end

end
